%YAML:1.0
---

nodes:
  #Is VICON Node
  0:
    has_uwb: true
    has_armarkers: true
    has_camera: true
    has_vo: true
    is_static: false
    has_global_pose: false
    anntena_pos: [-0.083, 0, 0.078]
    armarker_size : 0.0925
    bias:
      1: 0.21075
      2: 0.136
      3: 0.16
      4: 0.16

  1:
    has_uwb: true
    has_armarkers: true
    has_camera: true
    has_vo: true
    is_static: false
    has_global_pose: false
    anntena_pos: [-0.083, 0, 0.078]
    bias:
      0: 0.21075
      2: 0.1335
      3: 0.16
      4: 0.16

  2:
    has_uwb: true
    has_armarkers: true
    has_camera: true
    has_vo: true
    is_static: false
    has_global_pose: false
    anntena_pos: [-0.083, 0, 0.078]
    bias:
      0: 0.136
      1: 0.1335
      3: 0.16
      4: 0.16
  3:
    has_uwb: true
    has_armarkers: true
    has_camera: true
    has_vo: true
    is_static: false
    has_global_pose: false
    anntena_pos: [-0.083, 0, 0.078]
    bias:
      0: 0.16
      1: 0.16
      2: 0.16
      4: 0.16
  4:
    has_uwb: true
    has_armarkers: true
    has_camera: true
    has_vo: true
    is_static: false
    has_global_pose: false
    anntena_pos: [-0.083, 0, 0.078]
    bias:
      0: 0.16
      1: 0.16
      2: 0.16
      3: 0.16